# CRE Project Settings
staging-settings:
  rpcs:
    - chain-name: ethereum-mainnet-base-1
      url: https://mainnet.base.org
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
